---
- hosts: db
  become: true
  tasks:
    - name: Update apt packages
      apt: update_cache=yes

    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB
      service:
        name: mongodb
        state: started
        enabled: yes
